version: '3'
services:
  postgres:
    image: postgres:14.7-alpine3.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    ports:
      - 8082:8080

  # localstack:
  #   image: localstack/localstack:1.4.0
  #   environment:
  #     - LOCALSTACK_SERVICES=s3
  #     - LS_LOG=info
  #     - AWS_DEFAULT_REGION=us-east-1
  #     - AWS_ACCESS_KEY_ID=dummyaccess
  #     - AWS_SECRET_ACCESS_KEY=dummysecret
  #     - SKIP_SSL_CERT_DOWNLOAD=1
  #   volumes:
  #     - ./localstack/data:/var/lib/localstack
  #     - ./localstack/init.sh:/etc/localstack/init/ready.d/init.sh
  #   ports:
  #     - 4566:4566